# Generated by Django 2.1 on 2018-08-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=100)),
                ('image_coordinates', models.TextField()),
            ],
        ),
    ]
